config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :api do
    resources :users, only: :show # Maybe this route as controller/method has been superceded
    get '/user_by_email' => 'user_by_email#show', as: :user_by_email
  end

  resources :prefecture, only: :show

  resources :city, only: %i[index new show]
  post 'city/new', to: 'city#create'
  get 'city/:id/edit', to: 'city#edit', as: 'edit_city'
  patch 'city/:id/edit', to: 'city#update'
  put 'city/:id/edit', to: 'city#update'
  delete 'city/:id', to: 'city#destroy'

  resources :waste_type, only: %i[new show]
  post 'waste_type/new', to: 'waste_type#create'
  get 'waste_type/:id/edit', to: 'waste_type#edit', as: 'edit_waste_type'
  patch 'waste_type/:id/edit', to: 'waste_type#update'
  put 'waste_type/:id/edit', to: 'waste_type#update'
  delete 'waste_type/:id', to: 'waste_type#destroy'

  resources :profile, only: :show
  get 'profile/:id/edit', to: 'profile#edit', as: 'edit_profile'
  patch 'profile/:id/edit', to: 'profile#update'
  put 'profile/:id/edit', to: 'profile#update'
  post 'profile/:id/approve', to: 'profile#approve', as: 'approve_profile'

  resources :user, only: :index
end

app/controllers/waste_type_controller.rb
# frozen_string_literal: true

class WasteTypeController < ApplicationController
  def show
    @waste_type = WasteType.find_by(id: params[:id])
    @city = City.find_by(id: @waste_type.city_identifier)
  end

  def new
    @city = City.find_by(id: params[:format])
    @rule_days = RuleDay.where(city_id: params[:format]).order(:code)
    @waste_type = WasteType.new
    session[:city_id] = params[:format]
  end

  def create
    @city = City.find_by(id: session[:city_id])
    @rule_days = RuleDay.where(city_id: session[:city_id]).order(:code)
    @waste_type = WasteType.new(params.require(:waste_type).permit(:rule_day_id, :name, :description, :instructions,
                                                                   :irregular_frequency))
    @waste_type.city_identifier = session[:city_id]

    respond_to do |format|
      format.html do
        if @waste_type.save
          flash[:success] = 'Waste type saved successfully'
          redirect_to city_path(@city)
          session.delete(:city_id)
        else
          flash.now[:error] = 'Error: Waste type could not be saved'
          render :new, locals: { waste_type: @waste_type }, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @waste_type = WasteType.find_by(id: params[:id])
    @city = City.find_by(id: @waste_type.city_identifier)
    @rule_days = RuleDay.where(city_id: @city.id).order(:code)
    respond_to do |format|
      format.html { render :edit, locals: { waste_type: @waste_type } }
    end
  end

  def update
    @waste_type = WasteType.find_by(id: params[:id])
    @city = City.find_by(id: @waste_type.city_identifier)
    @rule_days = RuleDay.where(city_id: @city.id).order(:code)

    respond_to do |format|
      format.html do
        if @waste_type.update(params.require(:waste_type).permit(:name, :description, :instructions,
                                                                 :irregular_frequency, :rule_day_id))
          flash[:success] = 'Rule updated successfully'
          redirect_to city_path(@city)
        else
          flash.now[:error] = 'Error: Rule could not be updated'
          render :edit, locals: { waste_type: @waste_type }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @waste_type = WasteType.find(params[:id])
    @waste_type.destroy
    @city = City.find_by(id: @waste_type.city_identifier)

    respond_to do |format|
      format.html do
        flash[:success] = 'Rule removed successfully'
        redirect_to city_path(@city)
      end
    end
  end
end

app/views/waste_type/_waste_type_display.html.erb
<div class="flex justify-center mt-2">
    <div class="text-left w-full sm:w-1/2 sm:text-sm font-normal">
        <p class="border-b text-sm mb-1 font-semibold">Type</p>
        <p class="mb-3"><%= @waste_type.name %></p>
        <% if @waste_type.description.present? %>
            <p class="border-b text-sm mb-1 font-semibold">Description</p>
            <p class="mb-3"><%= @waste_type.description %></p>
        <% end %>
        <% if @waste_type.instructions.present? %>
            <p class="border-b text-sm mb-1 font-semibold">Disposal instructions</p>
            <p class="mb-3"><%= @waste_type.instructions %></p>
        <% end %>
        <% if @waste_type.irregular_frequency.present? %>
            <p class="border-b text-sm mb-1 font-semibold">Irregular collection frequency</p>
            <p class="mb-3"><%= @waste_type.irregular_frequency %></p>
        <% end %>
    </div>
</div>
<div class="space-y-4 mt-2">
    <%= link_to "Edit", edit_waste_type_path(@waste_type), class: "main-button w-full sm:w-1/2 inline-flex items-center justify-center px6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800" %>
    <%= button_to "Delete", waste_type_path(@waste_type), class: "main-button w-full sm:w-1/2 inline-flex items-center justify-center px6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800", method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #{@waste_type.name}?" } } %>
</div>

app/views/waste_type/_waste_type_edit_form.html.erb
<%= form_with model: @waste_type, url: edit_waste_type_path, method: :patch, local: true, scope: :waste_type do |f| %>
    <div class="w-full sm:w-1/2 inline-block mt-4">
        <div class="shadow-sm -space-y-px focus:z-10">
            <div>
                <%= f.label :rule_day_id, "Day", class: "sr-only" %>
                <%= f.collection_select :rule_day_id, @rule_days, :id, :name, { prompt: 'Day' }, { class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" } %>
            </div>
            <div>
                <%= f.label :name, "Waste type", class: "sr-only" %>
                <%= f.text_field :name, autofocus: true, placeholder: "Waste type", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :description, "Description", class: "sr-only" %>
                <%= f.text_area :description, autofocus: true, placeholder: "Description", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :instructions, "Disposal instructions", class: "sr-only" %>
                <%= f.text_area :instructions, autofocus: true, placeholder: "Disposal instructions", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :irregular_frequency, "Irregularities in collection schedule", class: "sr-only" %>
                <%= f.text_area :irregular_frequency, autofocus: true, placeholder: "Irregularities in collection schedule", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
        </div>
        <div>
            <%= f.submit "Update", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800" %>
        </div>
    </div>
<% end %>

app/views/waste_type/_waste_type_new_form.html.erb
<%= form_with model: @waste_type, url: waste_type_new_path, method: :post, local: true, scope: :waste_type do |f| %>
    <div class="w-full sm:w-1/2 inline-block mt-4">
        <div class="shadow-sm -space-y-px focus:z-10">
            <div>
                <%= f.label :rule_day_id, "Day", class: "sr-only" %>
                <%= f.collection_select :rule_day_id, @rule_days, :id, :name, { prompt: 'Day' }, { class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" } %>
            </div>
            <div>
                <%= f.label :name, "Waste type", class: "sr-only" %>
                <%= f.text_field :name, autofocus: true, placeholder: "Waste type", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :description, "Description", class: "sr-only" %>
                <%= f.text_area :description, autofocus: true, placeholder: "Description", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :instructions, "Disposal instructions", class: "sr-only" %>
                <%= f.text_area :instructions, autofocus: true, placeholder: "Disposal instructions", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :irregular_frequency, "Irregularities in collection schedule", class: "sr-only" %>
                <%= f.text_area :irregular_frequency, autofocus: true, placeholder: "Irregularities in collection schedule", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
        </div>
        <div>
            <%= f.submit "Add", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800" %>
        </div>
    </div>
<% end %>

app/views/waste_type/edit.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: 'Edit a rule', 
    description: "Update details for #{@city.name}: #{@waste_type.name}", 
    page_content: 'waste_type_edit_form' 
%>

app/views/waste_type/new.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: 'Add a rule', 
    description: "Add a recycling rule for #{@city.name}", 
    page_content: 'waste_type_new_form' 
%>

app/views/waste_type/show.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: "#{@city.prefecture.name}: #{@city.name}", 
    description: "Maybe it'd be nice to replace this with a modal eventually...", 
    page_content: 'waste_type_display' 
%>