config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :api do
    resources :users, only: :show # Maybe this route as controller/method has been superceded
    get '/user_by_email' => 'user_by_email#show', as: :user_by_email
  end

  resources :prefecture, only: :show

  resources :city, only: %i[index new show]
  post 'city/new', to: 'city#create'
  get 'city/:id/edit', to: 'city#edit', as: 'edit_city'
  patch 'city/:id/edit', to: 'city#update'
  put 'city/:id/edit', to: 'city#update'
  delete 'city/:id', to: 'city#destroy'

  resources :waste_type, only: %i[new show]
  post 'waste_type/new', to: 'waste_type#create'
  get 'waste_type/:id/edit', to: 'waste_type#edit', as: 'edit_waste_type'
  patch 'waste_type/:id/edit', to: 'waste_type#update'
  put 'waste_type/:id/edit', to: 'waste_type#update'
  delete 'waste_type/:id', to: 'waste_type#destroy'

  resources :profile, only: :show
  get 'profile/:id/edit', to: 'profile#edit', as: 'edit_profile'
  patch 'profile/:id/edit', to: 'profile#update'
  put 'profile/:id/edit', to: 'profile#update'
  post 'profile/:id/approve', to: 'profile#approve', as: 'approve_profile'

  resources :user, only: :index
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates :name, presence: true
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :prefecture, presence: true

  has_many :rule_days, dependent: :destroy

  belongs_to :prefecture

  after_create :create_rule_days

  private

  def create_rule_days
    { 1 => 'Monday', 2 => 'Tuesday', 3 => 'Wednesday', 4 => 'Thursday', 5 => 'Friday', 6 => 'Saturday',
      7 => 'Sunday' }.each do |code, name|
      rule_days << RuleDay.create(code:, name:)
      save!
    end
  end
end

app/controllers/city_controller.rb
# frozen_string_literal: true

class CityController < ApplicationController
  def index
    @cities = City.all.order(:name)
  end

  def show
    @city = City.find(params[:id])
    @waste_types = WasteType.where(city_identifier: @city.id).includes(:rule_day).order('rule_days.code', :name)
  end

  def new
    @prefectures = Prefecture.all.order(:code)
    @city = City.new
    return unless params[:format].present?

    @city.prefecture_id = params[:format]
  end

  def create
    @prefectures = Prefecture.all.order(:code)
    @city = City.new(params.require(:city).permit(:name, :prefecture_id))
    @city.rating = 0

    respond_to do |format|
      format.html do
        if @city.save
          flash[:success] = 'City saved successfully'
          redirect_to city_index_path
        else
          flash.now[:error] = 'Error: City could not be saved'
          render :new, locals: { city: @city }, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @prefectures = Prefecture.all.order(:code)
    @city = City.find(params[:id])
    respond_to do |format|
      format.html { render :edit, locals: { city: @city } }
    end
  end

  def update
    @prefectures = Prefecture.all.order(:code)
    @city = City.find(params[:id])

    respond_to do |format|
      format.html do
        if @city.update(params.require(:city).permit(:name, :prefecture_id, :rating))
          flash[:success] = 'City updated successfully'
          redirect_to city_path(@city)
        else
          flash.now[:error] = 'Error: City could not be updated'
          render :edit, locals: { city: @city }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html do
        flash[:success] = 'City removed successfully'
        redirect_to city_index_path
      end
    end
  end
end

app/views/city/_cities_display.html.erb
<div>
    <%= link_to "Add a city", new_city_path, class: "main-button w-full sm:w-1/2 inline-flex items-center justify-center px6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800 mt-2" %>
    <div class="flex justify-center text-left"> 
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table>
                        <thead class="bg-white border-b">
                            <tr>
                                <th scope="col" class="p-4">
                                    Prefecture
                                </th>
                                <th scope="col" class="p-4">
                                    City
                                </th>
                                <th scope="col" class="p-4">
                                    Rules
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @cities.each do |city| %>
                                <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                    <td class="p-4 text-teal-500 hover:text-teal-300 focus:underline"><%= link_to city.prefecture.name, prefecture_path(city.prefecture) %></td>
                                    <td class="p-4 text-teal-500 hover:text-teal-300 focus:underline"><%= link_to city.name, city_path(city) %></td>
                                    <td class="p-4 font-normal text-center"><%= get_number_of_rules_by_city_id(city) %></td> 
                                    <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline">
                                        <%= link_to edit_city_path(city) do %>
                                            <%= inline_svg_tag('svg/edit_icon.svg', class: 'w-5 h-5') %>
                                        <% end %>
                                    </td>
                                    <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline delete-button">
                                        <%= button_to city_path(city), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #{city.name}?" } } do %>
                                            <%= inline_svg_tag('svg/delete_icon.svg', class: 'h-5 w-5') %>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/city/_city_display.html.erb
<div class="mt-2">
    <p>Prefecture: <%= link_to @city.prefecture.name, prefecture_path(@city.prefecture), class: "px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline" %></p>
    <p>Rating: <%= @city.rating %></p>
    <span class="inline-flex">
        <%= link_to edit_city_path(@city), class: "px-2 py-3 text-teal-500 hover:text-teal-300 focus:underline" do %>
            <%= inline_svg_tag('svg/edit_icon.svg', class: 'w-5 h-5') %>
        <% end %>
        <%= button_to city_path(@city), class: "px-2 py-3 text-teal-500 hover:text-teal-300 focus:underline delete-button", method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #{@city.name}?" } } do %>
            <%= inline_svg_tag('svg/delete_icon.svg', class: 'h-5 w-5') %>
        <% end %>
    </span>
</div>
<div class="border-t">
    <h4 class="text-2xl leading-6 text-gray-900 mt-3 mb-4">Rules</h4>
    <%= link_to "Add a rule", new_waste_type_path(@city), class: "main-button w-full sm:w-1/2 inline-flex items-center justify-center px6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800" %>
</div>
<div class="flex justify-center text-left"> 
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table>
                        <thead class="bg-white border-b">
                            <tr>
                                <th scope="col" class="p-4">
                                    Day
                                </th>
                                <th scope="col" class="p-4">
                                    Name
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @waste_types.each do |waste_type| %>
                                <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                    <td class="p-4"><%= waste_type.rule_day.name %></td>
                                    <td class="p-4 text-teal-500 hover:text-teal-300 focus:underline"><%= link_to waste_type.name, waste_type_path(waste_type) %></td>
                                    <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline">
                                        <%= link_to edit_waste_type_path(waste_type) do %>
                                            <%= inline_svg_tag('svg/edit_icon.svg', class: 'w-5 h-5') %>
                                        <% end %>
                                    </td>
                                    <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline delete-button">
                                        <%= button_to waste_type_path(waste_type), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #{waste_type.name}?" } } do %>
                                            <%= inline_svg_tag('svg/delete_icon.svg', class: 'h-5 w-5') %>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

app/views/city/_city_edit_form.html.erb
<%= form_with model: @city, url: edit_city_path, method: :patch, local: true, scope: :city do |f| %>
    <div class="w-full sm:w-1/2 inline-block mt-4">
        <div class="shadow-sm -space-y-px focus:z-10">
            <div>
                <%= f.label :prefecture_id, "Prefecture", class: "sr-only" %>
                <%= f.collection_select :prefecture_id, @prefectures, :id, :name, { prompt: 'Prefecture' }, { class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" } %>
            </div>
            <div>
                <%= f.label :name, "City name", class: "sr-only" %>
                <%= f.text_field :name, autofocus: true, placeholder: "City name", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
            <div>
                <%= f.label :rating, "Rating", class: "sr-only" %>
                <%= f.number_field :rating, min: 0, max: 5, step: 0.1, autofocus: true, placeholder: "City rating", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 sm:text-sm mb-4" %>
            </div>
        </div>
        <div>
            <%= f.submit "Update", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800" %>
        </div>
    </div>
<% end %>

app/views/city/_city_new_form.html.erb
<%= form_with model: @city, url: new_city_path, method: :post, local: true, scope: :city do |f| %>
    <div class="w-full sm:w-1/2 inline-block mt-4">
        <div class="rounded-md shadow-sm -space-y-px">
            <div>
                <%= f.label :prefecture_id, "Prefecture", class: "sr-only" %>
                <%= f.collection_select :prefecture_id, @prefectures, :id, :name, { prompt: 'Prefecture' }, { class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 focus:z-10 sm:text-sm mb-4" } %>
            </div>
            
            <div>
                <%= f.label :name, "City name", class: "sr-only" %>
                <%= f.text_field :name, autofocus: true, placeholder: "City name", class: "appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 rounded-md focus-within:ring-1 focus-within:ring-slate-800 focus-within:border-slate-800 focus:z-10 sm:text-sm mb-4" %>
            </div>
        </div>
        <div>
            <%= f.submit "Add", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800" %>
        </div>
    </div>
<% end %>

app/views/city/edit.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: 'Edit', 
    description: 'Update name, prefecture and rating', 
    page_content: 'city_edit_form' 
%>

app/views/city/index.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: 'Cities', 
    description: '', 
    page_content: 'cities_display' 
%>

app/views/city/new.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: 'Add a city', 
    description: "Create a new city in the database. Once the rules model it set up you'll be able to add rules to it", 
    page_content: 'city_new_form' 
%>

app/views/city/show.html.erb
<%= render 'layouts/authorization_filter', 
    page_title: "#{@city.name}", 
    description: "Display/edit information for #{@city.name}", 
    page_content: 'city_display' 
%>