config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :api do
    resources :users, only: :show # Maybe this route as controller/method has been superceded
    get '/user_by_email' => 'user_by_email#show', as: :user_by_email
  end

  resources :prefecture, only: :show

  resources :city, only: %i[index new show]
  post 'city/new', to: 'city#create'
  get 'city/:id/edit', to: 'city#edit', as: 'edit_city'
  patch 'city/:id/edit', to: 'city#update'
  put 'city/:id/edit', to: 'city#update'
  delete 'city/:id', to: 'city#destroy'

  resources :waste_type, only: %i[new show]
  post 'waste_type/new', to: 'waste_type#create'
  get 'waste_type/:id/edit', to: 'waste_type#edit', as: 'edit_waste_type'
  patch 'waste_type/:id/edit', to: 'waste_type#update'
  put 'waste_type/:id/edit', to: 'waste_type#update'
  delete 'waste_type/:id', to: 'waste_type#destroy'

  resources :profile, only: :show
  get 'profile/:id/edit', to: 'profile#edit', as: 'edit_profile'
  patch 'profile/:id/edit', to: 'profile#update'
  put 'profile/:id/edit', to: 'profile#update'
  post 'profile/:id/approve', to: 'profile#approve', as: 'approve_profile'

  resources :user, only: :index
end

app/models/prefecture.rb
# frozen_string_literal: true

class Prefecture < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :code, presence: true, uniqueness: true

  has_many :cities, dependent: :destroy
end

app/controllers/prefecture_controller.rb
# frozen_string_literal: true

class PrefectureController < ApplicationController
  def show
    @prefecture = Prefecture.find(params[:id])
    @cities = City.where(prefecture_id: @prefecture.id)
  end
end

app/helpers/prefecture_helper.rb
# frozen_string_literal: true

module PrefectureHelper
  def get_number_of_cities_by_prefecture_id(params)
    City.where(prefecture_id: params[:id]).count
  end

  def get_number_of_rules_by_city_id(params)
    WasteType.where(city_identifier: params[:id]).count
  end
end

app/views/prefecture/_prefecture_display.html.erb
<% if @cities.count == 0 %>
    <%= link_to "Add a city", new_city_path(@prefecture), class: "main-button w-full sm:w-1/2 inline-flex items-center justify-center px6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-teal-500 hover:bg-teal-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-800 mt-2" %>
<% else %>
    <div class="flex justify-center text-left">
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table>
                        <thead class="bg-white border-b">
                            <tr>
                                <th scope="col" class="p-4">
                                    City
                                </th>
                                <th scope="col" class="p-4">
                                    Rating
                                </th>
                                <th scope="col" class="p-4">
                                    Rules
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @cities.each do |city| %>
                                <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                    <td class="p-4 text-teal-500 hover:text-teal-300 focus:underline"><%= link_to city.name, city_path(city) %></td>
                                    <td class="px-6 py-4 font-normal text-center"><%= city.rating %></td>
                                    <td class="px-6 py-4 font-normal text-center"><%= get_number_of_rules_by_city_id(city) %></td>
                                    <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline">
                                        <%= link_to edit_city_path(city) do %>
                                            <%= inline_svg_tag('svg/edit_icon.svg', class: 'w-5 h-5') %>
                                        <% end %>
                                    </td>
                                    <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline delete-button">
                                        <%= button_to city_path(city), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #{city.name}?" } } do %>
                                            <%= inline_svg_tag('svg/delete_icon.svg', class: 'h-5 w-5') %>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div> 
<% end %>

app/views/prefecture/show.html.erb
<% if @cities.count == 0 %>
    <%= render 'layouts/authorization_filter', 
        page_title: "There are no cities listed yet for #{@prefecture.name}", 
        description: "",
        page_content: 'prefecture_display'
    %>
<% else %>
     <%= render 'layouts/authorization_filter', 
        page_title: "Cities for #{@prefecture.name}",
        description: "", 
        page_content: 'prefecture_display'
    %>
<% end %>