config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :api do
    resources :users, only: :show # Maybe this route as controller/method has been superceded
    get '/user_by_email' => 'user_by_email#show', as: :user_by_email
  end

  resources :prefecture, only: :show

  resources :city, only: %i[index new show]
  post 'city/new', to: 'city#create'
  get 'city/:id/edit', to: 'city#edit', as: 'edit_city'
  patch 'city/:id/edit', to: 'city#update'
  put 'city/:id/edit', to: 'city#update'
  delete 'city/:id', to: 'city#destroy'

  resources :waste_type, only: %i[new show]
  post 'waste_type/new', to: 'waste_type#create'
  get 'waste_type/:id/edit', to: 'waste_type#edit', as: 'edit_waste_type'
  patch 'waste_type/:id/edit', to: 'waste_type#update'
  put 'waste_type/:id/edit', to: 'waste_type#update'
  delete 'waste_type/:id', to: 'waste_type#destroy'

  resources :profile, only: :show
  get 'profile/:id/edit', to: 'profile#edit', as: 'edit_profile'
  patch 'profile/:id/edit', to: 'profile#update'
  put 'profile/:id/edit', to: 'profile#update'
  post 'profile/:id/approve', to: 'profile#approve', as: 'approve_profile'

  resources :user, only: :index
end

app/views/layouts/_authorization_filter.html.erb
<div data-controller="authorization-filter" class="text-md font-medium text-gray-900 text-center">
    <div class="p-4">
        <h4 class="text-2xl leading-6 text-gray-900 mt-2"><%= page_title %></h4>
        <div class="mt-2">
            <% if approved_user?(user_signed_in?, current_user&.profile) %>
                <p class="font-normal"><%= description %></p>
                <%= render page_content if page_content %>
            <% elsif user_signed_in? %>
                <p>Your account is pending approval. If you have not already done so please <%= link_to 'update', profile_path(current_user&.profile), class: "text-teal-500 hover:text-teal-300 focus:underline" %> your profile.</p>
            <% else %>
                <p>This area is for approved admin users. Please <a data-authorization-filter-target="userAuthLink" class="text-teal-500 hover:text-teal-300 focus:underline cursor-pointer">sign up</a> or <a data-authorization-filter-target="userAuthLink" class="text-teal-500 hover:text-teal-300 focus:underline cursor-pointer">log in</a>.</p>
            <% end %>
        </div>
    </div>
</div>

<%= render 'shared/modal', modal_content: 'shared/user_auth_form' %>

app/views/layouts/_header.html.erb
<header data-controller="header" class="bg-slate-800">
    <div class="max-w-7xl mx-auto px-2 sm:px-4 lg:px-8">
        <div class="relative h-16 flex justify-between nav-container">
            <div class="relative z-10 px-2 flex lg:px-0">
                 <div class="flex-shrink-0 flex items-center">
                    <%= link_to root_path, class: "logo-link flex items-center focus:underline" do %>
                        <%= inline_svg_tag('svg/recycle_icon.svg') %>
                        <h1 class="text-xl font-bold pl-2">Mottainai Admin</h1> 
                    <% end %>
                </div>
            </div>

            <div data-header-target="openNavBarMenu" class="relative z-10 flex items-center visible md:invisible">
                <button type="button" class="rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:bg-slate-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-teal-300">
                <span class="sr-only">Open menu</span>
                <%= inline_svg_tag('svg/burger_icon.svg', class: 'block h-6 w-6') %>
            </div>

            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0 invisible md:visible">
                <button type="button" class="p-1 rounded-full text-gray-400 hover:text-teal-300 focus:outline-none focus:ring-2 focus:ring-teal-300">
                    <span class="sr-only">View notifications</span>
                    <%= inline_svg_tag('svg/bell_icon.svg', class: 'h-6 w-6') %>
                </button>

                <div class="ml-3 relative">
                    <div>
                        <button data-header-target="openUserMenu" type="button" class="bg-teal-500 hover:bg-teal-300 rounded-full flex items-center justify-center text-lg text-white h-8 w-8 focus:outline-none focus:ring-2 focus:ring-teal-300" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                            <span class="sr-only">Open user menu</span>
                            <%= user_profile_initials(user_signed_in?, current_user&.profile) %>
                        </button>
                    </div>

                    <div 
                        class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none divide-y divide-slate-200 z-20" 
                        id="menu-dropdown-items"
                        role="menu" 
                        aria-orientation="vertical" 
                        aria-labelledby="user-menu-button" 
                        tabindex="-1"
                        data-transition-enter="transition ease-out duration-100"
                        data-transition-enter-start="transform opacity-0 scale-95"
                        data-transition-enter-end="transform opacity-100 scale-100"
                        data-transition-leave="transition ease-in duration-75"
                        data-transition-leave-start="transform opacity-100 scale-100"
                        data-transition-leave-end="transform opacity-0 scale-95"
                    >
                        <div class="py-1 text-sm text-gray-700" role="none">
                            <% if user_signed_in? %>
                                <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "block px-4 py-2 hover:bg-gray-100" %>
                                <%= link_to "View profile", profile_path(current_user&.profile), class: "block px-4 py-2 hover:bg-gray-100" %>
                                <%= link_to "Edit profile", edit_profile_path(current_user&.profile), class: "block px-4 py-2 hover:bg-gray-100" %>
                            <% else %>
                                <a href="#" data-header-target="userAuthLink" class="block px-4 py-2 hover:bg-gray-100" role="menuitem" tabindex="-1" id="user-menu-item-0">Sign up</a>
                                <a href="#" data-header-target="userAuthLink" class="block px-4 py-2 hover:bg-gray-100" role="menuitem" tabindex="-1" id="user-menu-item-1">Log in</a>
                            <% end %>
                        </div>
                        
                        <div class="py-1 text-sm text-gray-700" role="none">
                            <% if approved_user?(user_signed_in?, current_user&.profile) %>
                                <%= link_to "Cities", city_index_path, class: "block px-4 py-2 hover:bg-gray-100", id: "user-menu-item-2" %>
                                <%= link_to "Add a city", new_city_path, class: "block px-4 py-2 hover:bg-gray-100", id: "user-menu-item-3" %>
                                <%= link_to "Users", user_index_path, class: "block px-4 py-2 hover:bg-gray-100", id: "user-menu-item-3" %>
                            <% else %>
                                <p class="block px-4 py-2" role="menuitem" tabindex="-1" id="user-menu-item-1">Restricted</p>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- Mobile menu-->
    <nav 
        class="hidden" 
        id="nav-bar-menu"
        role="menu" 
        aria-orientation="vertical" 
        aria-labelledby="user-menu-button" 
        tabindex="-1"
        data-transition-enter="transition ease-out duration-100"
        data-transition-enter-start="transform opacity-0 scale-95"
        data-transition-enter-end="transform opacity-100 scale-100"
        data-transition-leave="transition ease-in duration-75"
        data-transition-leave-start="transform opacity-100 scale-100"
        data-transition-leave-end="transform opacity-0 scale-95"
    >
        <div class="border-t border-gray-700 pt-4 pb-3">
            <div class="px-4 flex items-center">
                <div class="flex-shrink-0">
                    <div class="bg-teal-500 rounded-full flex items-center justify-center text-lg text-white h-10 w-10" aria-expanded="false" aria-haspopup="true">
                        <%= user_profile_initials(user_signed_in?, current_user&.profile) %>
                    </div>
                </div>   
                <div class="ml-3">
                    <div class="text-base font-medium text-gray-700"><%= user_profile_full_name(user_signed_in?, current_user&.profile) %></div>
                    <div class="text-sm font-medium text-gray-400"><%= current_user&.email %></div>
                </div>
                <button type="button" class="ml-auto p-1 rounded-full text-gray-400 hover:text-teal-300 focus:outline-none focus:ring-2 focus:ring-teal-300">                        
                    <span class="sr-only">View notifications</span>
                    <%= inline_svg_tag('svg/bell_icon.svg', class: 'h-6 w-6') %>
                </button>
                <div class="mt-3 px-2 space-y-1 text-sm text-base font-medium text-gray-700">
                    <% if user_signed_in? %>
                        <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "block rounded-md py-2 px-3 focus:bg-gray-700 focus:text-white" %>
                        <%= link_to "View profile", profile_path(current_user&.profile), class: "block rounded-md py-2 px-3 focus:bg-gray-700 focus:text-white" %>
                        <%= link_to "Edit profile", edit_profile_path(current_user&.profile), class: "block rounded-md py-2 px-3 focus:bg-gray-700 focus:text-white" %>
                    <% else %>
                        <a href="#" data-header-target="userAuthLink" class="block rounded-md py-2 px-3 focus:bg-gray-700 focus:text-white" role="menuitem" tabindex="-1" id="user-menu-item-0">Sign up</a>
                        <a href="#" data-header-target="userAuthLink" class="block rounded-md py-2 px-3 focus:bg-gray-700 focus:text-white" role="menuitem" tabindex="-1" id="user-menu-item-1">Log in</a>
                    <% end %>
                    <% if approved_user?(user_signed_in?, current_user&.profile) %>
                        <%= link_to "Cities", city_index_path, class: "block rounded-md py-2 px-3 hover:bg-gray-700 hover:text-white", id: "user-menu-item-2" %>
                        <%= link_to "Add a city", new_city_path, class: "block rounded-md py-2 px-3 hover:bg-gray-700 hover:text-white", id: "user-menu-item-3" %>
                        <%= link_to "Users", user_index_path, class: "block rounded-md py-2 px-3 hover:bg-gray-700 hover:text-white", id: "user-menu-item-4" %>
                    <% end %>
                </div>
            </div>
        </div>
    </nav>
</header>

<%= render 'shared/modal', modal_content: 'shared/user_auth_form' %>

app/views/layouts/_messages.html.erb
<% if flash[:success].present? %>
    <div class="bg-teal-100 border-t-4 border-teal-500 text-teal-900 px-4 py-3 shadow-md" role="alert">
        <div class="flex">
            <div>
                <p class="font-bold"><%= flash[:success] %></p>
            </div>
        </div>
    </div>
<% end %>
<% if flash[:error].present? %>
    <div class="bg-rose-100 border-t-4 border-rose-500 text-rose-900 px-4 py-3 shadow-md" role="alert">
        <div class="flex">
            <div>
                <p class="font-bold"><%= flash[:error] %></p>
            </div>
        </div>
    </div>
<% end %>
<!-- <% if flash[:notice].present? %>
    <div class="bg-blue-100 border-t-4 border-blue-500 text-blue-900 px-4 py-3 shadow-md" role="alert">
        <div class="flex">
            <div>
                <p class="font-bold"><%= flash[:notice] %></p>
            </div>
        </div>
    </div>
<% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motainai Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path("svg/recycle_favicon.svg") %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>